# Generated by Django 4.2.1 on 2023-05-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albums.team'),
            preserve_default=False,
        ),
    ]
