# Generated by Django 4.2.1 on 2023-05-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_listener_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Label',
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': 'labels'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='publisher',
            new_name='label',
        ),
    ]
