# Generated by Django 4.2.1 on 2023-05-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist',
        ),
    ]
