# Generated by Django 4.2.1 on 2023-05-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_artist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
