# Generated by Django 4.2.1 on 2023-05-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_rename_artist_album_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
