# Generated by Django 4.2.1 on 2023-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0019_remove_favorite_album_remove_listener_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
