# Generated by Django 4.2.1 on 2023-05-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0020_alter_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.label'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='album',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listener',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albums.team'),
            preserve_default=False,
        ),
    ]
