# Generated by Django 4.2.1 on 2023-05-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0021_rename_artist_artist_name_album_label_favorite_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('song_list', models.TextField()),
                ('published_date', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.label')),
            ],
        ),
    ]
