# Generated by Django 4.2.1 on 2023-05-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0022_vinyl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.artist'),
        ),
        migrations.DeleteModel(
            name='Vinyl',
        ),
    ]
